export const UPDATE_INGREDIENT = "UPDATE_INGREDIENT";
export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const FETCH_INGREDIENTS_FAILED= "FETCH_INGREDIENTS_FAILED";

export const ORDER_SUBMIT_COMPLETE = "ORDER_SUBMIT_COMPLETE";
export const ORDER_SUBMIT_FAILED = "ORDER_SUBMIT_COMPLETE_FAILED";
export const ORDER_SUBMIT_STARTED = "ORDER_SUBMIT_COMPLETE_STARTED";
export const CONTACT_FORM_INPUT_CHANGED = "CONTACT_FORM_INPUT_CHANGED";

export const ORDERS_FETCH_COMPLETE = "ORDERS_FETCH_COMPLETE";
export const ORDERS_FETCH_FAILED = "ORDERS_FETCH_FAILED";
export const ORDERS_FETCH_STARTED = "ORDERS_FETCH_STARTED";

export const AUTH_STARTED = "AUTH_STARTED";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILURE = "AUTH_FAILURE";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";